---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - На странице корзины пользователь cможет удалить товар из корзины
  - На странице корзины пользователь cможет продолжить выбирать товары в каталоге
  - На странице корзины пользователь cможет оформить заказ с переходом на страницу оплаты
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  - Сайт должен сохранять товары после перезаходе пользователя на сайт
  - Сайт должен быть постоянно доступен (не падать) 
  - Сайт должен работать как SPA (Single Page Application)
  - На странице товара и в каталоге выводится название, рейтинг, цена со скидкой и без нее
  
implicit:
  - Товары на сайте дожны соответствовать законам РФ
  - При добавлении товара из каталога в корзину цены не должны различаться 
  - Пользователь не может редактировать описание товара
  - Переход на главную страницу сайт можеть быть осуществлен из любойчасти страницы
  - Верно отслеживается количество товара в каталоге по каждой позиции
  


